/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DocDocApp {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLDocDocAppElement extends Components.DocDocApp, HTMLStencilElement {
    }
    var HTMLDocDocAppElement: {
        prototype: HTMLDocDocAppElement;
        new (): HTMLDocDocAppElement;
    };
    interface HTMLElementTagNameMap {
        "doc-doc-app": HTMLDocDocAppElement;
    }
}
declare namespace LocalJSX {
    interface DocDocApp {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "doc-doc-app": DocDocApp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "doc-doc-app": LocalJSX.DocDocApp & JSXBase.HTMLAttributes<HTMLDocDocAppElement>;
        }
    }
}
